---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    groups:
      dependencies:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    groups:
      dependencies:
        update-types:
          - "minor"
          - "patch"
