volumes:
  data:

services:
  hej:
    image: ghcr.io/srittau/hej:latest
    build: .
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - data:/app/data
    environment:
      - UVICORN_WORKERS=1
      - HEJ_SESSION_KEY=sikrit
      - HEJ_DEBUG=true
