---
version: 1
formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  access:
    format: "%(asctime)s %(message)s"
handlers:
  access:
    level: INFO
    class: logging.FileHandler
    formatter: access
    filename: /app/log/access.log
  error:
    level: WARNING
    class: logging.FileHandler
    formatter: standard
    filename: /app/log/error.log
  stdout:
    level: INFO
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout
loggers:
  "uvicorn.access":
    level: INFO
    handlers: [access, stdout]
    propagate: no
root:
  level: INFO
  handlers: [error, stdout]
