[tool.black]
line-length = 79
target-version = ["py310"]

[tool.isort]
profile = "black"
combine_as_imports = true
line_length = 79
known_hej = "hej"
known_hejtest = "test_hej"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,HEJ,HEJTEST,LOCALFOLDER"

[tool.pytest.ini_options]
testpaths = ["pylibs"]

[tool.mypy]
disallow_any_decorated = true
disallow_any_generics = true
disallow_any_unimported = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
no_implicit_optional = true
no_implicit_reexport = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true
