[tool.poetry]
name = "hej"
version = "0.1.0"
description = "Simple browser-based personal wiki"
authors = ["Sebastian Rittau <srittau@rittau.biz>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.11"
aiofiles = ">=23.2.1"
aiosqlite = "~0.19.0"
ariadne = "~0.21"
dbupgrade = "^2023.10.0"
click = "^8.0.3"
graphql-core = "^3.1.7"
starlette = "~0.34.0"
uvicorn = { version = "~0.25.0", extras = ["standard"] }

[tool.poetry.group.dev.dependencies]
asserts = "^0.12.0"
black = "^23.12.1"
flake8 = "^7.0.0"
isort = "^5.13.2"
mypy = "~1.8.0"
poethepoet = "^0.24.4"
pytest = "*"
pytest-asyncio = "^0.23.3"
pytest-mock = "^3.12.0"
types-aiofiles = "^23.2.0.20240106"

[tool.black]
line-length = 79
target-version = ["py311"]

[tool.isort]
profile = "black"
combine_as_imports = true
line_length = 79
known_hej = "hej"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,HEJ,LOCALFOLDER"

[tool.pytest.ini_options]
testpaths = ["pylibs"]
asyncio_mode = "auto"

[tool.mypy]
disallow_any_decorated = true
disallow_any_generics = true
disallow_any_unimported = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
no_implicit_optional = true
no_implicit_reexport = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.poe.tasks]
test = "pytest"
lint = "flake8 pylibs"
typecheck = "mypy pylibs"

[tool.poe.tasks.start]
cmd = "uvicorn --reload hej.app:app"
[tool.poe.tasks.start.env]
PYTHONPATH = "pylibs"
HEJ_SESSION_KEY = "sikrit"
HEJ_DB_PATH = "test-db/hej.sqlite"
