[tool.poetry]
name = "hej"
version = "0.1.0"
description = "Simple browser-based personal wiki"
authors = ["Sebastian Rittau <srittau@rittau.biz>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.11"
aiofiles = "~23.1.0"
aiosqlite = "~0.19.0"
ariadne = "~0.19.0"
click = "^8.0.3"
graphql-core = "^3.1.7"
starlette = "~0.26.0"
uvicorn = { version = "~0.22.0", extras = ["standard"] }

[tool.poetry.dev-dependencies]
black = "^23.1.0"
flake8 = "^6.0.0"
isort = "^5.10.1"
mypy = "~1.2.0"
pytest = "*"
pytest-asyncio = "^0.21.0"
types-aiofiles = "^23.1.0.0"

[tool.black]
line-length = 79
target-version = ["py310"]

[tool.isort]
profile = "black"
combine_as_imports = true
line_length = 79
known_hej = "hej"
known_hejtest = "test_hej"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,HEJ,HEJTEST,LOCALFOLDER"

[tool.pytest.ini_options]
testpaths = ["pylibs"]
asyncio_mode = "strict"

[tool.mypy]
disallow_any_decorated = true
disallow_any_generics = true
disallow_any_unimported = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
no_implicit_optional = true
no_implicit_reexport = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true
