---
name: Test and build hej

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: pip
      - name: Install poetry
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
        run: pip install poetry==1.1.12
      - name: Install Python packages
        run: poetry install
      - name: Type check with mypy
        run: poetry run mypy --no-incremental pylibs
      - name: Lint with flake8
        run: poetry run flake8 pylibs
      - name: Run tests with pytest
        run: poetry run pytest

  test-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          cache: yarn
      - name: Install npm packages
        run: yarn install --frozen-lockfile
      - name: Lint TypeScript with ESLint
        run: yarn run lint
      - name: Check formatting with prettier
        run: yarn run prettier
      - name: Run tests with jest
        run: CI=true yarn run test

  build-docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - test-python
      - test-javascript
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker images
          docker-compose build --pull
          docker images
