---
name: Test and build hej

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:

permissions:
  contents: read
  packages: write

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: srittau/hej

jobs:
  test-python:
    name: Test Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: "**/poetry.lock"
      - name: Install poetry
        run: pip --disable-pip-version-check install -U poetry
      - name: Install Python packages
        run: poetry install
      - name: Type check with mypy
        run: poetry run poe typecheck --no-incremental
      - name: Lint with ruff
        run: poetry run poe lint
      - name: Run tests with pytest
        run: poetry run poe test

  test-javascript:
    name: Test JavaScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: yarn
      - name: Install npm packages
        run: yarn install --frozen-lockfile
      - name: Lint TypeScript
        run: yarn run lint
      - name: Check formatting
        run: yarn run prettier
      - name: Run tests
        run: yarn run test:ci

  build-docker:
    name: Build and Publish Docker image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - test-python
      - test-javascript
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker images
          docker compose build --pull
          docker images
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image
        run: docker compose push
