---
name: Test and build hej

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: pip
      - name: Install Python packages
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
        run: |
          pip install --upgrade pip setuptools
          pip install -r requirements.txt
          pip check
      - name: Type check with mypy
        run: mypy --no-incremental pylibs
      - name: Lint with flake8
        run: flake8 pylibs
      - name: Run tests with pytest
        run: pytest

  test-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: yarn
      - name: Install npm packages
        run: yarn install --frozen-lockfile
      - name: Lint TypeScript with ESLint
        run: yarn run lint
      - name: Check formatting with prettier
        run: yarn run prettier
      - name: Run tests with jest
        run: CI=true yarn run test
