---
name: Test and build hej

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: npm
      - name: Install npm packages
        run: yarn install --frozen-lockfile
      - name: Lint TypeScript with ESLint
        run: yarn run lint
      - name: Check formatting with prettier
        run: yarn run prettier
      - name: Run tests with jest
        run: CI=true yarn run test
